# Generated by Django 3.2.6 on 2021-08-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
