# Generated by Django 3.2.6 on 2021-08-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
