# Generated by Django 3.2.6 on 2021-08-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groovin', '0002_posts_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
    ]
